fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    param_fetcher_listener: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    view:
        view_response_listener:  true
    exception:
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            Doctrine\ORM\EntityNotFoundException: 404
            \LogicException: 400
            \DomainException: 400
        messages:
            Doctrine\ORM\EntityNotFoundException: true
            \LogicException: true
            \DomainException: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            # - { path: ^/, stop: true } # FOSRest should not handle other routes than API
            - { path: ^/, priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }